package com.abysscore.exgc;

public final class ExgNative {
    static {
        System.loadLibrary("exg");
    }

    private ExgNative() {}

    public static native int start(String filesDir);
    public static native void shutdown();
    public static native void tick();
    public static native int connect();
    public static native void disconnect();
    public static native boolean connected();
    public static native String status();
    public static native boolean statusOk();
    public static native float sps();
    public static native int frames();
    public static native int copyWave(int ch, float[] dst);
    public static native int scaleUv();
    public static native void cycleScale();
    public static native int windowS();
    public static native void cycleWindow();
    public static native void setActive(int ch, boolean on);
    public static native void setRld(int ch, boolean on);
    public static native void cycleGain(int ch);
    public static native boolean active(int ch);
    public static native boolean rld(int ch);
    public static native int gain(int ch);
    public static native int color(int ch);
    public static native void cycleColor(int ch);
    public static native void setColor(int ch, int rgb);
    public static native void setScaleUv(int uv);
    public static native void setWindowS(int s);
    public static native void setNotch(int hz);
    public static native void setHp(int hz);
    public static native void setLp(int hz);
    public static native void setBand(int band);
    public static native void setAlgo(int id);
    public static native void setUiScale(int tenths);
    public static native void setBoardImu(boolean imu);
    public static native void setGain(int ch, int gain);
    public static native void calStart();
    public static native int calPhase();
    public static native int calProgress();
    public static native String calLine();
    public static native void noiseArm();
    public static native void noiseOk();
    public static native void calm();
    public static native void toggleClean();
    public static native boolean calHave();
    public static native boolean calmHave();
    public static native boolean cleanOn();
    public static native boolean cleanLive();
    public static native void setName(String s);
    public static native String getName();
    public static native void record();
    public static native void toggleMatch();
    public static native boolean matchOn();
    public static native void setProfile(String s);
    public static native String getProfile();
    public static native int profSave();
    public static native int profLoad();
    public static native int profDel();
    public static native int profRename(String s);
    public static native String[] profiles();
    public static native String ports();
    public static native void cyclePort();
    public static native void setPortI(int i);
    public static native void copyCube(byte[] dst);
    public static native void leftoverUv(float[] dst);
    public static native int pairN();
    public static native String pairLabel(int i);
    public static native void pairChs(int i, int[] dst);
    public static native void pairUv(float[] dst);
    public static native void cycleNotch();
    public static native void cycleHp();
    public static native int notch();
    public static native int notchEff();
    public static native int hp();
    public static native int lp();
    public static native void cycleLp();
    public static native boolean car();
    public static native void toggleCar();
    public static native boolean detrend();
    public static native void toggleDetrend();
    public static native boolean envelope();
    public static native void toggleEnvelope();
    public static native int band();
    public static native void cycleBand();
    public static native boolean clipped(int ch);
    public static native int algo();
    public static native void cycleAlgo();
    public static native String algoName();
    public static native void togglePause();
    public static native boolean paused();
    public static native boolean csvOn();
    public static native void toggleCsv();
    /* Fills up to 64 bins (128-pt strip). Returns peak Hz. */
    public static native int copyFft(float[] dst);
    public static native void toggleAtom();
    public static native void atomStart();
    public static native int atomStop();
    public static native boolean atomOn();
    public static native int atomN();
    public static native int atomSave();
    public static native int atomLoad();
    public static native float atomUnity();
    public static native String atomLine();
    public static native String atomRef();
    public static native int atomCount();
    public static native String atomAt(int i);
    public static native int atomSecs(int i);
    public static native int atomSelect(int i);
    public static native void atomDel(int i);
    public static native void atomDiscard();
    public static native void atomPick(int i);
    public static native String atomPair();
    public static native String atomSlotA();
    public static native String atomSlotB();
    public static native int atomIdBest();
    public static native float atomIdScore(int i);

    public static native int cubeView();
    public static native void setCubeView(int map);
    public static native void cubeSpin(float yaw, float pitch);
    public static native void cubeZoom(int dir);
    public static native void cubeFront();
    public static native boolean cubeFloat();
    public static native void toggleCubeFloat();
    public static native int elecSel();
    public static native void setElecSel(int ch);
    public static native String elecLabel(int ch);
    public static native String elecName(int ch);
    public static native void elecXyz(int ch, float[] xyz);
    public static native int siteFocus();
    public static native void siteStep(int dir);
    public static native void assignSite(int site);
    public static native int siteN();
    public static native String siteName(int i);
    public static native boolean siteCore(int i);
    public static native int siteCh(int i);
    public static native void siteFlat(int i, float[] xy);
    public static native void siteXyz(int i, float[] xyz);
    public static native String siteFocusLabel();
    public static native int vizCells(float[] xyz, float[] size, int[] rgba);
    public static native int smxSeq();
    public static native int smxFold();
    public static native int profExport(String path);
    public static native int profImport(String path);
    public static native String idLine();
    public static native int recMs();
    public static native String matchLine();
    public static native int learnN();
    public static native String learnName(int i);
    public static native float learnScore(int i);
    public static native float learnScoreCube(int i);
    public static native int learnBest();
    public static native int learnSel();
    public static native void learnSelect(int i);
    public static native void learnDel(int i);
    public static native boolean imuOk();
    public static native void imu(float[] dst);
    public static native boolean boardImu();
    public static native void cycleBoard();
    public static native int uiScale();
    public static native void cycleUiScale();

    public static native boolean apiOn();
    public static native void setApiOn(boolean on);
    public static native boolean apiLan();
    public static native void setApiLan(boolean lan);
    public static native int apiHz();
    public static native void setApiHz(int hz);
    public static native int apiHttp();
    public static native void setApiHttp(int port);
    public static native int apiUdp();
    public static native void setApiUdp(int port);
    public static native int apiTcp();
    public static native void setApiTcp(int port);
    public static native String apiToken();
    public static native void setApiToken(String s);
    public static native String apiPush();
    public static native void setApiPush(String s);
    public static native String apiLine();
}
